version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nalgebra-glm
    versions:
    - 0.10.0
    - 0.11.0
  - dependency-name: minifb
    versions:
    - 0.19.2
