name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'

  - title: 'Bugfixes'
    labels:
      - 'bug'

  - title: 'Documentation'
    labels:
      - 'documentation'

exclude-labels:
  - 'chore'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## Changes

  $CHANGES
